@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

TutorBook *-right-> "1" UniqueStudentList
TutorBook *-right-> "1" EnrolmentList
TutorBook *-right-> "1" UniqueLessonList
UniqueStudentList -[hidden]down- EnrolmentList
EnrolmentList -[hidden]down- UniqueLessonList

UniqueStudentList -right-> "*" Student
UniqueLessonList -right-> "*" Lesson
EnrolmentList -right-> "*" Enrolment

Enrolment -up-> "1" Student
Enrolment -down-> "1" Lesson
@enduml
