@startuml
!include style.puml
skinparam ClassFontColor #000000
skinparam ClassBorderColor #000000
skinparam ClassBackgroundColor #FFFFAA

title After command "deletestudent 5"

package States <<rectangle>> {
    class State1 as "<u>tb0:TutorBook</u>"
    class State2 as "<u>tb1:TutorBook</u>"
    class State3 as "<u>tb2:TutorBook</u>"
}

State1 -[hidden]right-> State2
State2 -[hidden]right-> State3

hide State3

class Pointer as "Current State" #FFFFFF

Pointer -up-> State2
@end
